<?php
/**
 * lnks — web installer
 * Creates config.php on first run. Refuses to run once config.php exists.
 */

$root = __DIR__;
require_once $root . '/layout.php';

/* ── Lock: never run twice ───────────────────────────────────────── */
if (file_exists($root . '/config.php')) {
    http_response_code(403);
    installPage('Already installed', '
        <h1>Already installed</h1>
        <p class="muted">config.php already exists. For security, the installer is disabled.</p>
        <p class="muted">To reconfigure, edit config.php manually or delete it and reload this page.</p>
        <p><a href="/">Go to homepage</a> · <a href="/admin.php">Admin panel</a></p>
    ');
    exit;
}

/* ── Environment checks ──────────────────────────────────────────── */
$checks = [
    'PHP 8.0+'            => PHP_VERSION_ID >= 80000,
    'PDO SQLite'          => extension_loaded('pdo_sqlite'),
    'storage/ writable'   => is_writable($root . '/storage') || @mkdir($root . '/storage', 0775, true),
    'root dir writable'   => is_writable($root), // needed to write config.php
];
$envOk = !in_array(false, $checks, true);

/* ── Handle submit ───────────────────────────────────────────────── */
$errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $envOk) {
    $pass1 = $_POST['password'] ?? '';
    $pass2 = $_POST['password2'] ?? '';
    $publicForm = isset($_POST['public_form']);

    if (strlen($pass1) < 8)   $errors[] = 'Password must be at least 8 characters.';
    if ($pass1 !== $pass2)    $errors[] = 'Passwords do not match.';

    if (!$errors) {
        $hash  = password_hash($pass1, PASSWORD_BCRYPT);
        $token = bin2hex(random_bytes(24));
        $scheme  = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
        $host    = $_SERVER['HTTP_HOST'] ?? '';
        $baseUrl = preg_match('~^[A-Za-z0-9.\-]+(:\d+)?$~', $host) ? $scheme . '://' . $host : '';

        $config = "<?php\n"
            . "/**\n * lnks — configuration (generated by install.php)\n */\n"
            . "return [\n"
            . "    'app_name'   => 'lnks',\n"
            . "    'base_url'   => " . var_export($baseUrl, true) . ",\n"
            . "    'timezone'   => 'UTC',\n"
            . "    'db_path'    => __DIR__ . '/storage/lnks.sqlite',\n"
            . "    'admin_pass_hash' => " . var_export($hash, true) . ",\n"
            . "    'api_token'  => " . var_export($token, true) . ",\n"
            . "    'public_form' => " . var_export($publicForm, true) . ",\n"
            . "    'trust_proxy' => false,   // true only behind your own reverse proxy (reads X-Forwarded-For)\n"
            . "    'code' => [\n"
            . "        'alphabet' => 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789',\n"
            . "        'length'   => 6,\n"
            . "    ],\n"
            . "];\n";

        if (file_put_contents($root . '/config.php', $config, LOCK_EX) === false) {
            $errors[] = 'Could not write config.php — check directory permissions.';
        } else {
            @chmod($root . '/config.php', 0640);
            // Initialize the database right away
            require $root . '/bootstrap.php';
            db();

            installPage('Installed', '
                <h1>Done<span class="accent">.</span></h1>
                <p>lnks is installed and ready.</p>
                <div class="kv">
                    <div><span class="muted">Admin panel</span><br><a href="/admin.php">' . e($baseUrl) . '/admin.php</a></div>
                    <div><span class="muted">API token</span><br><code>' . e($token) . '</code></div>
                </div>
                <p class="muted">Save the API token now — it is stored only in config.php.
                For extra safety you may delete install.php from the server.</p>
                <p><a href="/">Go to homepage</a></p>
            ');
            exit;
        }
    }
}

/* ── Render form ─────────────────────────────────────────────────── */
$checkRows = '';
foreach ($checks as $name => $ok) {
    $checkRows .= '<li class="' . ($ok ? 'ok' : 'fail') . '">'
        . ($ok ? '&#10003;' : '&#10007;') . ' ' . e($name) . '</li>';
}

$errorHtml = '';
foreach ($errors as $e) {
    $errorHtml .= '<p class="error">' . e($e) . '</p>';
}

installPage('Install', '
    <h1>Setup<span class="accent">.</span></h1>
    <ul class="checks">' . $checkRows . '</ul>
    ' . ($envOk ? '
    ' . $errorHtml . '
    <form method="post" class="login">
        <input type="password" name="password" placeholder="Admin password (min 8 chars)" required minlength="8">
        <input type="password" name="password2" placeholder="Repeat password" required minlength="8">
        <label class="checkbox">
            <input type="checkbox" name="public_form" checked>
            Allow anyone to shorten links from the homepage
        </label>
        <button type="submit" class="btn">Install</button>
    </form>
    <p class="muted small">The API token will be generated automatically and shown after install.</p>
    ' : '<p class="error">Fix the failed checks above, then reload this page.</p>') . '
');

/* ── Standalone layout (works before config exists) ─────────────── */
function installPage(string $title, string $body): void {
    renderLayout($title, '<section class="hero">' . $body . '</section>', ['nav' => 'none', 'narrow' => true, 'app' => 'lnks']);
}
